
import json
import os
import shlex
from pathlib import Path

GWAK_OUTPUT_DIR = GWAK_ROOT / "gwak" / "output"
STATE_DIR = GWAK_ROOT / ".gwak"
BOOTSTRAP_DIR = STATE_DIR / "bootstrap"
PATHS_FILE = STATE_DIR / "paths.json"
ENV_FILE = STATE_DIR / "env.sh"
ENVIRONMENT_FILE = GWAK_ROOT / "gwak/data/environment.data.yaml"

# --------------------------------------------------
# Default GWAK environment variables
# --------------------------------------------------
DEFAULT_PATHS = {
    "GWAK_ROOT"                : GWAK_ROOT,
    # Directory for saving outputs including models, logs, checkpoints, and intermediate results
    "GWAK_OUTPUT_DIR"          : GWAK_OUTPUT_DIR,
    # Top-level directory containing different versions of GWAK dataset
    "GWAK_DATA_DIR"            : GWAK_OUTPUT_DIR / "data",
    # Directory for storing visualization artifacts and plots
    "GWAK_LOUVRE_DIR"          : GWAK_OUTPUT_DIR / "plots",
    # Directory for storing log files or compressed out/err.log from working nodes.
    "GWAK_LOG_DIR"             : GWAK_OUTPUT_DIR,
    # Dataset directory for O4 MDC BBC short-0/1
    "GWAK_BBC_SHORT_0_DATA_DIR": GWAK_OUTPUT_DIR / "data" / "O4_MDC_short-0",
    "GWAK_BBC_SHORT_1_DATA_DIR": GWAK_OUTPUT_DIR / "data" / "O4_MDC_short-1",
    # Top-level directory to write or save container images
    "IMAGE_DIR"                : Path.home() / "Container" / "GWAK",
    # Local directory for collecting outputs generated by containerized jobs
    "CONTAIN_OUTPUT_DIR"       : Path.home() / "Container" / "GWAK",
    # # CIT html
    # "CIT_html": Path.home() /  "public_html"
}

def resolve_configured_path(name, fallback):
    configured = config.get(name.lower())
    if configured:
        return Path(configured).expanduser()
    return fallback


def build_paths():
    paths = {
        key: resolve_configured_path(key, fallback)
        for key, fallback in DEFAULT_PATHS.items()
    }
    data_dir = paths["GWAK_DATA_DIR"]
    paths["GWAK_BBC_SHORT_0_DATA_DIR"] = resolve_configured_path(
        "GWAK_BBC_SHORT_0_DATA_DIR",
        data_dir / "O4_MDC_short-0",
    )
    paths["GWAK_BBC_SHORT_1_DATA_DIR"] = resolve_configured_path(
        "GWAK_BBC_SHORT_1_DATA_DIR",
        data_dir / "O4_MDC_short-1",
    )
    return {key: str(value) for key, value in paths.items()}


GWAK_PATHS = build_paths()
OUTPUT_DIR                = Path(GWAK_PATHS["GWAK_OUTPUT_DIR"])
DATA_DIR                  = Path(GWAK_PATHS["GWAK_DATA_DIR"])
LOUVRE_DIR                = Path(GWAK_PATHS["GWAK_LOUVRE_DIR"])
LOG_DIR                   = Path(GWAK_PATHS["GWAK_LOG_DIR"])
BBC_SHORT_0_DATA_DIR      = Path(GWAK_PATHS["GWAK_BBC_SHORT_0_DATA_DIR"])
BBC_SHORT_1_DATA_DIR      = Path(GWAK_PATHS["GWAK_BBC_SHORT_1_DATA_DIR"])
IMAGE_DIR                 = Path(GWAK_PATHS["IMAGE_DIR"])
CONTAIN_OUTPUT_DIR        = Path(GWAK_PATHS["CONTAIN_OUTPUT_DIR"])

CONDA_ENV_NAME = config.get("conda_env_name", "gwak-data")

localrules:
    bootstrap_submodules,
    bootstrap_paths,
    bootstrap_conda_data_env,
    bootstrap_complete

rule bootstrap_submodules:
    output:
        done=str(BOOTSTRAP_DIR / "submodules.done"),
    shell:
        """
        set -euo pipefail
        git submodule sync --recursive
        git submodule update --init --recursive
        touch {output.done}
        """

rule bootstrap_paths:
    output:
        paths=str(PATHS_FILE),
        env=str(ENV_FILE),
    run:
        STATE_DIR.mkdir(parents=True, exist_ok=True)
        BOOTSTRAP_DIR.mkdir(parents=True, exist_ok=True)

        for key, value in GWAK_PATHS.items():
            Path(value).mkdir(parents=True, exist_ok=True)

        with open(output.paths, "w", encoding="utf-8") as f:
            json.dump(GWAK_PATHS, f, indent=2, sort_keys=True)
            f.write("\n")

        lines = [
            "# Auto-generated by `snakemake -c1 gwak-init`.",
            "# Source this file only if you want the same paths in your shell.",
        ]
        for key, value in sorted(GWAK_PATHS.items()):
            quoted = shlex.quote(value)
            lines.append(f"export {key}={quoted}")
        with open(output.env, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))
            f.write("\n")

rule bootstrap_conda_data_env:
    input:
        env_file=str(ENVIRONMENT_FILE),
    output:
        done=str(BOOTSTRAP_DIR / "conda-data.done"),
    params:
        env_name=CONDA_ENV_NAME,
        repo_root=shlex.quote(str(GWAK_ROOT)),
    shell:
        """
        set -euo pipefail
        if conda env list | awk '{{print $1}}' | grep -Fxq "{params.env_name}"; then
            conda env update --name {params.env_name} --file {input.env_file} --prune
        else
            conda env create --name {params.env_name} --file {input.env_file}
        fi
        conda run --no-capture-output -n {params.env_name} python -m pip install -e {params.repo_root}
        touch {output.done}
        """

rule bootstrap_complete:
    input:
        rules.bootstrap_submodules.output.done,
        rules.bootstrap_paths.output,
        rules.bootstrap_conda_data_env.output,
    output:
        "gwak-init",
    params:
        env_name=CONDA_ENV_NAME,
    shell:
        """
        set -euo pipefail
        cat <<EOF > {output}
        GWAK bootstrap complete.
        Conda env: {params.env_name}
        Paths file: {PATHS_FILE}
        Shell exports: {ENV_FILE}
        EOF
        """

rule build_deploy_containers:
    input:
        deploy_container = GWAK_ROOT / "gwak/deploy/deploy.def"
    output:
        deploy_image =  IMAGE_DIR / "deploy.sif"
    params:
        processors = "--mksquashfs-args '-processors 32'"
    shell:
        "set -x; apptainer build {params.processors} \
        {output.deploy_image} {input.deploy_container}"
