import json
import shlex
from copy import deepcopy
from pathlib import Path
import yaml


STATE_DIR = GWAK_ROOT / ".gwak"
BOOTSTRAP_DIR = STATE_DIR / "bootstrap"
PATHS_FILE = STATE_DIR / "paths.json"
ENV_FILE = STATE_DIR / "env.sh"
ENVIRONMENT_FILE = GWAK_ROOT / "gwak/data/environment.data.yaml"
PATH_CONFIG = config.get("paths", {})
SHELL_PATH_PREPEND = config.get("shell_path_prepend", [])


def load_yaml_config(path):
    if not path.exists():
        return {}
    with open(path, encoding="utf-8") as handle:
        return yaml.safe_load(handle) or {}


def deep_merge(base, overrides):
    merged = deepcopy(base)
    for key, value in overrides.items():
        if (
            isinstance(merged.get(key), dict)
            and isinstance(value, dict)
        ):
            merged[key] = deep_merge(merged[key], value)
        else:
            merged[key] = value
    return merged


cli_config = deepcopy(config)
merged_config = deep_merge(
    load_yaml_config(DEFAULT_CONFIG),
    load_yaml_config(LOCAL_SETUP_CONFIG_FILE),
)
config.clear()
config.update(deep_merge(merged_config, cli_config))

def as_bool(value, default=True):
    if value is None:
        return default
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        return value.strip().lower() in {"1", "true", "yes", "on"}
    return bool(value)


RUN_BOOTSTRAP_CONDA_DATA_ENV = as_bool(
    config.get("run_bootstrap_conda_data_env"),
    default=True,
)

PATH_DEFAULTS = {
    "GWAK_ROOT": lambda paths: GWAK_ROOT,
    "GWAK_OUTPUT_DIR": lambda paths: GWAK_ROOT / "gwak" / "output", # The future archive dir
    "GWAK_DATA_DIR": lambda paths: paths["GWAK_OUTPUT_DIR"] / "data",
    "GWAK_LOUVRE_DIR": lambda paths: paths["GWAK_OUTPUT_DIR"] / "plots",
    "GWAK_LOG_DIR": lambda paths: paths["GWAK_OUTPUT_DIR"],
    "GWAK_BBC_SHORT_0_DATA_DIR": lambda paths: paths["GWAK_DATA_DIR"] / "O4_MDC_short-0",
    "GWAK_BBC_SHORT_1_DATA_DIR": lambda paths: paths["GWAK_DATA_DIR"] / "O4_MDC_short-1",
    "GWAK_BENCHMAKR_DIR": lambda paths: Path.home() / "Outputs" / "GWAK" / "gwak-internal-benchmark", # The future output dir
    "IMAGE_DIR": lambda paths: Path.home() / "Container" / "GWAK",
    "CONTAIN_OUTPUT_DIR": lambda paths: Path.home() / "Container" / "GWAK",
}


def resolve_configured_path(name, default_builder, resolved_paths):
    configured = PATH_CONFIG.get(name.lower())
    if configured:
        return Path(configured).expanduser()
    return default_builder(resolved_paths)


def build_paths():
    resolved_paths = {}
    for key, default_builder in PATH_DEFAULTS.items():
        resolved_paths[key] = resolve_configured_path(key, default_builder, resolved_paths)
    return {key: str(value.resolve()) for key, value in resolved_paths.items()}


def bootstrap_complete_inputs(_wildcards):
    inputs = [
        rules.bootstrap_submodules.output.done,
        *rules.bootstrap_paths.output,
    ]
    if RUN_BOOTSTRAP_CONDA_DATA_ENV:
        inputs.append(rules.bootstrap_conda_data_env.output.done)
    return inputs


def build_shell_exports(paths):
    lines = [
        "# Auto-generated by `snakemake -c1 gwak_init`.",
        "# Source this file if you want the same GWAK environment variables in your shell.",
    ]
    if SHELL_PATH_PREPEND:
        expanded_entries = [
            str(Path(entry).expanduser().resolve())
            for entry in SHELL_PATH_PREPEND
        ]
        quoted_prefix = shlex.quote(":".join(expanded_entries))
        lines.append(f"export PATH={quoted_prefix}:$PATH")

    for key, value in sorted(paths.items()):
        lines.append(f"export {key}={shlex.quote(value)}")
    return lines


GWAK_PATHS = build_paths()
OUTPUT_DIR                = Path(GWAK_PATHS["GWAK_OUTPUT_DIR"])
DATA_DIR                  = Path(GWAK_PATHS["GWAK_DATA_DIR"])
LOUVRE_DIR                = Path(GWAK_PATHS["GWAK_LOUVRE_DIR"])
LOG_DIR                   = Path(GWAK_PATHS["GWAK_LOG_DIR"])
BBC_SHORT_0_DATA_DIR      = Path(GWAK_PATHS["GWAK_BBC_SHORT_0_DATA_DIR"])
BBC_SHORT_1_DATA_DIR      = Path(GWAK_PATHS["GWAK_BBC_SHORT_1_DATA_DIR"])
BENCHMAKR_DIR             = Path(GWAK_PATHS["GWAK_BENCHMAKR_DIR"])
IMAGE_DIR                 = Path(GWAK_PATHS["IMAGE_DIR"])
CONTAIN_OUTPUT_DIR        = Path(GWAK_PATHS["CONTAIN_OUTPUT_DIR"])
CONDA_ENV_NAME = config.get("conda_env_name", "gwak-data")

# Make file
BENCHMAKR_DIR.mkdir(parents=True, exist_ok=True)
IMAGE_DIR.mkdir(parents=True, exist_ok=True)

localrules:
    bootstrap_submodules,
    bootstrap_paths,
    bootstrap_conda_data_env,
    bootstrap_complete

rule bootstrap_submodules:
    output:
        done=str(BOOTSTRAP_DIR / "submodules.done"),
    shell:
        """
        set -euo pipefail
        git submodule sync --recursive
        git submodule update --init --recursive
        touch {output.done}
        """

rule bootstrap_paths:
    output:
        paths=str(PATHS_FILE),
        env=str(ENV_FILE),
    run:
        STATE_DIR.mkdir(parents=True, exist_ok=True)
        BOOTSTRAP_DIR.mkdir(parents=True, exist_ok=True)

        for key, value in GWAK_PATHS.items():
            Path(value).mkdir(parents=True, exist_ok=True)

        with open(output.paths, "w", encoding="utf-8") as f:
            json.dump(GWAK_PATHS, f, indent=2, sort_keys=True)
            f.write("\n")

        lines = build_shell_exports(GWAK_PATHS)
        with open(output.env, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))
            f.write("\n")

rule bootstrap_conda_data_env:
    input:
        env_file=str(ENVIRONMENT_FILE),
    output:
        done=str(BOOTSTRAP_DIR / "conda-data.done"),
    params:
        env_name=CONDA_ENV_NAME,
        repo_root=shlex.quote(str(GWAK_ROOT)),
    shell:
        """
        set -euo pipefail
        if conda env list | awk '{{print $1}}' | grep -Fxq "{params.env_name}"; then
            conda env update --name {params.env_name} --file {input.env_file} --prune
        else
            conda env create --name {params.env_name} --file {input.env_file}
        fi
        conda run --no-capture-output -n {params.env_name} python -m pip install -e {params.repo_root}
        touch {output.done}
        """

rule bootstrap_complete:
    input:
        bootstrap_complete_inputs,
    output:
        "gwak-init",
    params:
        env_name=CONDA_ENV_NAME,
        conda_bootstrap="enabled" if RUN_BOOTSTRAP_CONDA_DATA_ENV else "skipped",
    shell:
        """
        set -euo pipefail
        cat <<EOF > {output}
        GWAK bootstrap complete.
        Conda bootstrap: {params.conda_bootstrap}
        Conda env: {params.env_name}
        Paths file: {PATHS_FILE}
        Shell exports: {ENV_FILE}
        EOF
        """

rule gwak_info:
    message:
        "Printing GWAK configuration"
    run:
        print("=" * 80)
        print("GWAK configuration")
        print("=" * 80)

        # for name, value in sorted(globals().items()):
        #     # if name.startswith("GWAK"):
        #     print(f"{name:30} {value}")

        print("\nGWAK Paths:")
        for key in sorted(GWAK_PATHS):
            print(f"    {key:30} {GWAK_PATHS[key]}")

        print("\nOther initialization variables:")
        print(f"{'    CONDA_ENV_NAME':34} {CONDA_ENV_NAME}")
        print(f"{'    GWAK_ROOT':34} {GWAK_ROOT}")
        print(f"{'    STATE_DIR':34} {STATE_DIR}")
        print(f"{'    BOOTSTRAP_DIR':34} {BOOTSTRAP_DIR}")
        print(f"{'    PATHS_FILE':34} {PATHS_FILE}")
        print(f"{'    ENV_FILE':34} {ENV_FILE}")
        # print(f"{"    RUN_BOOTSTRAP_CONDA_DATA_ENV":34} {RUN_BOOTSTRAP_CONDA_DATA_ENV}")

        print("=" * 80)

rule build_deploy_containers:
    input:
        deploy_container = GWAK_ROOT / "gwak/deploy/deploy.def"
    output:
        deploy_image =  IMAGE_DIR / "deploy.sif"
    params:
        processors = "--mksquashfs-args '-processors 32'"
    shell:
        "set -x; apptainer build {params.processors} \
        {output.deploy_image} {input.deploy_container}"
