# lightning.pytorch==2.3.2
seed_everything: 0
trainer:
  callbacks:
    - class_path: callback.ValidationCallback
  accelerator: gpu
  devices: [1]
  # accelerator: auto
  # devices: auto
  strategy: ddp_find_unused_parameters_true
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
  max_epochs: 10
  check_val_every_n_epoch: 1
  accumulate_grad_batches: 1
ckpt_path: null
model:
  class_path: fm_models.NonLinearClassifier
  init_args:
    n_dims: 6
data:
  class_path: dataloader.SignalDataloader
  init_args:
    signal_classes:
      - "SineGaussian"
      - "BBH"
      - "Gaussian"
      - "Cusp"
      - "Kink"
      - "KinkKink"
      - "WhiteNoiseBurst"
      - "CCSN"
      - "Background"
      - "Glitch"
    priors:
      - class_path: gwak.data.prior.SineGaussianBBC # SineGaussian
      - class_path: gwak.data.prior.LAL_BBHPrior # BBH
      - class_path: gwak.data.prior.GaussianBBC # Gaussian
      - class_path: gwak.data.prior.CuspBBC # Cusp
      - class_path: gwak.data.prior.KinkBBC # Kink
      - class_path: gwak.data.prior.KinkkinkBBC # KinkKink
      - class_path: gwak.data.prior.WhiteNoiseBurstBBC # WhiteNoiseBurst
      - null # CCSN
      - null # Background
      - null # Glitch
    waveforms:
      - class_path: ml4gw.waveforms.SineGaussian # SineGaussian
        init_args:
          sample_rate: 0
          duration: 0
      - class_path: ml4gw.waveforms.IMRPhenomPv2 # BBH
        init_args: {}
      - class_path: ml4gw.waveforms.Gaussian # Gaussian
        init_args:
          sample_rate: 0
          duration: 0
      - class_path: ml4gw.waveforms.GenerateString # Cusp
        init_args:
          sample_rate: 0
      - class_path: ml4gw.waveforms.GenerateString # Kink
        init_args:
          sample_rate: 0
      - class_path: ml4gw.waveforms.GenerateString # KinkKink
        init_args:
          sample_rate: 0
      - class_path: ml4gw.waveforms.WhiteNoiseBurst # WhiteNoiseBurst
        init_args:
          sample_rate: 0
          duration: 0
      - null # CCSN
      - null # Background
      - null # Glitch
    extra_kwargs:
      - null # SineGaussian
      - ringdown_duration: 0.9 # BBH
      - null # Gaussian
      - null # Cusp
      - null # Kink
      - null # KinkKink
      - null # WhiteNoiseBurst
      - null # CCSN
      - null # Background
      - null # Glitch
    sample_rate: 4096
    kernel_length: 1.0
    psd_length: 64
    fduration: 1
    fftlength: 2
    batch_size: 256
    batches_per_epoch: 20
    num_workers: 4
    data_saving_file: null
    anneal_snr: true
    snr_init_factor: 10.0
    snr_anneal_epochs: 10