# lightning.pytorch==2.3.2
seed_everything: 0
trainer:
  callbacks:
    - class_path: callback.ValidationCallback
  accelerator: gpu
  devices: [0]
  # accelerator: auto
  # devices: auto
  #strategy: ddp_find_unused_parameters_true
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: gwak2_embeddings
      entity: gwak
  log_every_n_steps: 1
  max_epochs: 100
  limit_val_batches: 10
  check_val_every_n_epoch: 1
  accumulate_grad_batches: 1
ckpt_path: null
model:
  class_path: cl_models.Crayon
  init_args:
    num_ifos: 2
    num_timesteps: 2048
    d_output: 4
    d_contrastive_space: 4
    temperature: 0.5
    temperature_init: null # not annealing temp
    n_temp_anneal: 10
    supervised_simclr: true
    lr_opt: 1e-3
    lr_min: 1e-5
    cos_anneal: false
    cos_anneal_tmax: 50
    use_classifier: true
    num_classes: 9
    lambda_classifier: 2.0
    class_anneal_epochs: 50
    s4_kwargs:
      d_model: 256
      d_state: 64
      n_layers: 4
      dropout: 0.2
      prenorm: false
      dt_min: 0.001
      dt_max: 0.1
      lr: 1e-4
data:
  class_path: dataloader.SignalDataloader
  init_args:
    signal_classes:
      - "SineGaussian"
      - "MultiSineGaussian"
      - "BBH"
      - "Gaussian"
      - "Cusp"
      - "Kink"
      - "KinkKink"
      - "WhiteNoiseBurst"
      - "Background"
      # - "Glitch"
    priors:
      - class_path: gwak.data.prior.SineGaussianBBC
      - class_path: gwak.data.prior.MultiSineGaussianBBC
      - class_path: gwak.data.prior.LAL_BBHPrior
      - class_path: gwak.data.prior.GaussianBBC
      - class_path: gwak.data.prior.CuspBBC
      - class_path: gwak.data.prior.KinkBBC
      - class_path: gwak.data.prior.KinkkinkBBC
      - class_path: gwak.data.prior.WhiteNoiseBurstBBC
      - null
      # - null [0, 0.25, 0.25, 0.5]
    waveforms:
      - class_path: ml4gw.waveforms.SineGaussian
        init_args:
          sample_rate: 0
          duration: 0
      - class_path: ml4gw.waveforms.MultiSineGaussian
        init_args:
          sample_rate: 0
          duration: 0
      - class_path: ml4gw.waveforms.IMRPhenomPv2
        init_args: {}
      - class_path: ml4gw.waveforms.Gaussian
        init_args:
          sample_rate: 0
          duration: 0
      - class_path: ml4gw.waveforms.GenerateString
        init_args:
          sample_rate: 0
      - class_path: ml4gw.waveforms.GenerateString
        init_args:
          sample_rate: 0
      - class_path: ml4gw.waveforms.GenerateString
        init_args:
          sample_rate: 0
      - class_path: ml4gw.waveforms.WhiteNoiseBurst
        init_args:
          sample_rate: 0
          duration: 0
      - null
    extra_kwargs:
      - null
      - null
      - ringdown_duration: 0.9
      - null
      - null
      - null
      - null
      - null
      - null
    sample_rate: 4096
    kernel_length: 0.5
    psd_length: 64
    fduration: 1
    fftlength: 2
    batch_size: 256
    batches_per_epoch: 20
    num_workers: 4
    data_saving_file: null