# lightning.pytorch==2.3.2
seed_everything: 0
trainer:
  accelerator: gpu
  devices: [1]
  # accelerator: auto
  # devices: auto
  strategy: ddp_find_unused_parameters_true
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
  max_epochs: 50
  check_val_every_n_epoch: 1
  accumulate_grad_batches: 1
ckpt_path: null
model:
  class_path: models.gwak2
  init_args:
    num_ifos: 2
    num_timesteps: 2048
    #bottleneck: 8
    device_str: None
data:
  class_path: dataloader.SignalDataloader
  init_args:
    data_dir: /home/ethan.marx/aframe/data/train/background
    sample_rate: 2048
    kernel_length: 1 #0.09765625
    psd_length: 64
    fduration: 1
    fftlength: 2
    batch_size: 128
    batches_per_epoch: 128
    num_workers: 5
    prior: gwak.data.prior.SineGaussianLowFrequency
    waveform:
      class_path: ml4gw.waveforms.SineGaussian