project: train
image_version: train_test_v8.sif
wandb_mode: offline
max_concurrent_node: 1
cl_config: null
coh_mode: null
fm_config: null
condor_kwargs:
  request_cpus: 16
  request_memory: 32G
  request_disk: 64G
  accounting_group: ligo.dev.o4.burst.explore.test
