project: combination # slurm_overwrite
model_dir: null # slurm_overwrite
output_dir:
  class_path: gwak_output_dir
clean: True
background_batch_size: 2
stride_batch_size: 256 # slurm_overwrite
ifos: ["H1", "L1"] # slurm_overwrite
snapshotter_instances: 6
preproc_instances: 2
gwak_instances: 6
platform: TORCHSCRIPT # TENSORRT
highpass: 30
psd_length: 64 # slurm_overwrite
kernel_length: 1
fduration: 2
fftlength: 2
sample_rate: 4096 # slurm_overwrite
inference_rate: 4 # slurm_overwrite
device: cuda:0 # cuda:0
cl_config: torch_rbw_zp_resnet_do6_dcs128_epoch25 # slurm_overwrite
fm_config: NF_from_file_conditioning # slurm_overwrite