condor_nodes: 8
condor_kwargs:
  request_cpus: 4
  request_memory: 32G
  request_disk: 16G
  accounting_group: ligo.dev.o4.burst.explore.test
run_name: one_test
ifos: ["H1", "L1"]
psd_length: 64
Tb: 0
stride_batch_size: 256
sample_rate: 4096
fname:
  class_path: gwak_data_dir
  init_args:
    suffix: O4_MDC_background_small_scale
data_format: h5 # gwf
shifts: [0, 1]
project: combination
grpc_port: 8101
image: hermes/tritonserver:23.01
model_repo_dir: null
result_dir: null
server_patients: 20
monitor_patients: null
job_rate_limit: 1
inference_rate: 4
cl_config: null
fm_config: null
# cl_config: torch_rbw_zp_resnet_do6_dcs128_epoch25
# fm_config: NF_from_file_conditioning