cl_config: torch_rbw_zp_resnet_do6_dcs128_epoch25
fm_config: NF_from_file_conditioning
ifo_mode: HL
project: one_year
out_dir:
  class_path: gwak_louvre_dir
seg_num: 10
thereshold_level: 0.01
infer_sample_rate: 4
psd_length: 64
plotting: True
plot_padding: 20