project: /home/hongyin.chen/anti-gravity/gwak/gwak/output/infer/combination/torch_rbw_zp_resnet_do6_dcs128_epoch25_NF_from_file_conditioning_HL-O4_MDC_short-0_slide_10/inference_result
inference_sampling_rate: 4
