[project]
name = "deploy"
version = "0.1.0"
description = "Triton inference for GWAK"
authors = [
    { name = "Andy Chen", email = "andy.c.80297@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bokeh>=3.8.2",
    "cowsay>=6.1",
    "h5py>=3.15.1",
    "jsonargparse>=4.45.0",
    "matplotlib>=3.10.8",
    "ml4gw",
    "ml4gw-hermes",
    "machinery",
    "onnx>=1.17.0",
    "pyrate-limiter>=4.0.2",
    "scipy>=1.15.3",
    "torch==2.7.1",
    "torchaudio==2.7.1",
    "tqdm>=4.67.1",
    "transforms",
]

[dependency-groups]
dev = [
    "pytest~=7.0",
    "ipykernel>=7.1.0",
    "jupyter>=1.0.0,<2",
    "pytest~=7.3",
]

[tool.uv]
extra-index-url = ["https://pypi.nvidia.com/"]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu128" }
torchaudio = { index = "pytorch-cu128" }
ml4gw = { path = "../../ml4gw", editable = true }
ml4gw-hermes = { path = "../../hermes", editable = true }
machinery = {path = "../../libs/machinery", editable = true }
transforms = {path = "../../libs/transforms", editable = true }

[tool.hatch.build.targets.wheel]
packages = ["deploy"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
